### ISSUE TITLE
Vertical item's height can never become less than the defaultHeight

### ISSUE THREAD

**Issue by christophersansone** [runspired/smoke-and-mirrors#127]
If you set the `defaultHeight` of a `vertical-collection` to 100px, and the contents of a `vertical-item` are only 50px, the `vertical-item` will remain at 100px instead of being resized down to 50px.

From what I can tell, the reason is because the vertical item element's `style.minHeight` is set to `defaultHeight`.  When the item's height is calculated, the `minHeight` is overriding the true height.

It seems like the flow could work like this:
1. Prior to the vertical item being rendered, it would set `minHeight` to `defaultHeight`, like it does today.
2. Upon rendering the contents of the vertical item, it should remove `minHeight` so that the item's true height will display.
3. When the vertical item is culled, it would calculate the actual height prior to the contents being removed, then set that as the `minHeight`.  I believe this is happening today as well, except without (2), it winds up using the minimum height.

**Comment by runspired** [comment]
@christophersansone this is intentional as it turns out that removing minHeight causes the height to lose height entirely momentarily in newer versions of Chrome. Long term there is a fix for this by revisiting how the collection renders (a lot of virtualization is coming). Short term, this is unfortunately no fix for this other than to set defaultHeight to the minimum expected non-zero height.

**Comment by christophersansone** [comment]
@runspired Thanks, looking forward to the updates.  You rock.

**Comment by runspired** [comment]
Should be fixed by updating to `@html-next/vertical-collection` (now re-exported by this lib)
